apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
  labels:
    app: app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dep
  template:
    metadata:
      labels:
        app: app-dep
    spec:
      containers:
        - name: app-dep
          image: mfilahi/mfilahi_app:v2
          ports:
            - containerPort: 1337